 # Regla por default, se deja por que es buena práctica siempre
# establecerla, aun que solo exista una regla

all: TargetRun

TargetRun: 
		g++ -o salida.exe $(TARGET)
		clear
		./salida.exe   # Corriendo el codigo
		rm salida.exe  # Borrando el ejecutable
